name             'rails-geo'
maintainer       'Michael Kirk'
maintainer_email 'michael.john.kirk@gmail.com'
license          'MIT'
description      'Installs/Configures a box suitable for running a geospatial Rails application'
long_description 'Installs/Configures a box suitable for running a geospatial Rails application'
version          '0.1.0'
depends          'locale'
depends          'rbenv'
depends          'openssl'
depends          'postgresql'
depends          'postgis'
